# Use an official Node.js runtime as the base image
FROM node:21-alpine

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# # Copy the DocumentDB CA certificate and .env file
# COPY /config/global-bundle.pem /app/global-bundle.pem
COPY .env .env

# # Set environment variables
# ENV MONGO_URI=$MONGO_URI

# Expose the application port
EXPOSE 8080

# Start the application
CMD ["node", "server.js"]