name: Deploy to Elastic Beanstalk and S3

on:
  push:
    branches:
      - main  # or the branch you want to deploy from

jobs:
  deploy-backend:
    name: Deploy backend to AWS Elastic Beanstalk
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Align with the version used by Elastic Beanstalk

      - name: Install dependencies
        run: npm install

      - name: Package application
        run: |
          cd backend
          zip -r ../nodejs.zip . -x "node_modules/*" -x ".git/*"
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: 'survey-web-app'
          environment_name: 'survey-web-app-env'
          version_label: ${{ github.sha }}
          region: ${{ secrets.AWS_REGION_NAME }}
          deployment_package: nodejs.zip

  deploy-frontend:
    name: Deploy Frontend to S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies for frontend
        run: |
            cd frontend 
            npm install --force

      - name: Build frontend
        run: |
            cd frontend 
            npm run build
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION_NAME }}

      - name: Sync Build Folder to S3
        run: |
          aws s3 sync frontend/build s3://adg429.com/
